# Generated by Django 5.1.6 on 2025-07-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='photo',
        ),
        migrations.AddField(
            model_name='tweet',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp_uploads/'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
