# Generated by Django 5.1.6 on 2025-07-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_options_remove_tweet_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='photo_file',
        ),
    ]
