# Generated by Django 5.1.6 on 2025-07-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_remove_tweet_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_photos/'),
        ),
    ]
